-- ==============================================================================
-- FASE 1: ESTRUTURA DE AUTENTICAÇÃO E PERMISSÕES (SUPABASE) - CORRIGIDO
-- ==============================================================================
-- Este script configura as tabelas necessárias para gerenciar usuários, perfis e
-- permissões de acesso às casas (multi-usuário).
-- ORDEM DE EXECUÇÃO CORRIGIDA PARA EVITAR ERROS DE DEPENDÊNCIA

-- 1. CRIAR TABELAS PRIMEIRO (SEM POLICIES AINDA)

-- 1.1 Tabela de Perfis Públicos (profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  CONSTRAINT username_length CHECK (char_length(full_name) >= 3)
);

-- 1.2 Tabela Mestre de Casas (houses)
CREATE TABLE IF NOT EXISTS public.houses (
  code TEXT PRIMARY KEY, -- O código único (ex: 'CASA_47')
  name TEXT NOT NULL,    -- Nome amigável (ex: 'Casa de Praia')
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 1.3 Tabela de Permissões (house_permissions)
CREATE TABLE IF NOT EXISTS public.house_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house_code TEXT REFERENCES public.houses(code) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'editor', 'viewer')) DEFAULT 'viewer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  UNIQUE(house_code, user_id) -- Garante que não haja duplicatas
);

-- 2. HABILITAR RLS (Row Level Security) EM TUDO

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.houses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.house_permissions ENABLE ROW LEVEL SECURITY;

-- 3. CRIAR POLICIES (AGORA QUE TODAS AS TABELAS EXISTEM)

-- Policies para PROFILES
CREATE POLICY "Perfis são visíveis por todos os autenticados" ON public.profiles
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Usuários podem editar seu próprio perfil" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Policies para HOUSE_PERMISSIONS
CREATE POLICY "Usuário vê suas próprias permissões" ON public.house_permissions
  FOR SELECT USING (auth.uid() = user_id);

-- Policies para HOUSES (Aqui estava o erro antes: dependia de house_permissions)
CREATE POLICY "Usuários veem casas que têm permissão" ON public.houses
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.house_permissions
      WHERE house_code = houses.code
      AND user_id = auth.uid()
    )
  );

-- 4. AUTOMAÇÃO (TRIGGERS E FUNÇÕES)

-- Função para criar profile automaticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', new.email), 
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Gatilho (Trigger) na tabela auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Função Helper de Segurança (Para usar nas outras tabelas do sistema)
CREATE OR REPLACE FUNCTION public.has_access_to_house(house_code_param TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.house_permissions
    WHERE user_id = auth.uid()
    AND house_code = house_code_param
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
