-- Tabela para armazenar as faixas de Imposto de Renda
-- Permite que o usuário edite os valores anualmente
CREATE TABLE IF NOT EXISTS ir_brackets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_value NUMERIC NOT NULL, -- Valor mínimo da faixa
    max_value NUMERIC,          -- Valor máximo da faixa (NULL significa infinito/acima de...)
    rate NUMERIC NOT NULL,      -- Alíquota em porcentagem (ex: 7.5, 15, 22.5, 27.5)
    deduction NUMERIC NOT NULL, -- Valor a deduzir do imposto
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE), -- Ano de vigência
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE ir_brackets ENABLE ROW LEVEL SECURITY;

-- Política de leitura: permitir acesso a todos os usuários autenticados
CREATE POLICY "Enable read access for authenticated users" ON ir_brackets
    FOR SELECT USING (auth.role() = 'authenticated');

-- Política de atualização: permitir atualização para usuários autenticados
-- (Assumindo que todos os usuários autenticados podem gerenciar as configurações do sistema neste contexto)
CREATE POLICY "Enable update access for authenticated users" ON ir_brackets
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Política de inserção: permitir inserção para usuários autenticados
CREATE POLICY "Enable insert access for authenticated users" ON ir_brackets
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Política de deleção: permitir deleção para usuários autenticados
CREATE POLICY "Enable delete access for authenticated users" ON ir_brackets
    FOR DELETE USING (auth.role() = 'authenticated');

-- Inserir dados iniciais para 2026 (conforme solicitado na imagem)
INSERT INTO ir_brackets (min_value, max_value, rate, deduction, year) VALUES
(0, 2428.80, 0, 0, 2026),
(2428.81, 2826.65, 7.5, 182.16, 2026),
(2826.66, 3751.05, 15, 394.16, 2026),
(3751.06, 4664.68, 22.5, 675.49, 2026),
(4664.68, NULL, 27.5, 908.73, 2026);
