-- Tabela para armazenar os reviews do Airbnb
CREATE TABLE IF NOT EXISTS airbnb_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id TEXT UNIQUE, -- ID único do review vindo do Airbnb
  reservation_code TEXT NOT NULL, -- Código da reserva para vínculo
  guest_name TEXT,
  review_url TEXT,
  
  -- Avaliação Geral
  overall_rating INTEGER,
  public_comment TEXT,
  host_response TEXT,
  private_feedback TEXT,
  
  -- Feedback Detalhado
  cleanliness_rating INTEGER,
  accuracy_rating INTEGER,
  checkin_rating INTEGER,
  communication_rating INTEGER,
  location_rating INTEGER,
  value_rating INTEGER,
  
  -- Análise Qualitativa (Pilar 2)
  sentiment TEXT,
  positive_feedback_tags TEXT[],
  improvement_feedback_tags TEXT[],
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  house_code TEXT -- Para filtrar por casa/propriedade
);

-- Índice para busca rápida por código de reserva
CREATE INDEX IF NOT EXISTS idx_airbnb_reviews_reservation_code ON airbnb_reviews(reservation_code);

-- Habilitar RLS (Row Level Security) se necessário (recomendado)
ALTER TABLE airbnb_reviews ENABLE ROW LEVEL SECURITY;

-- Política de acesso (exemplo: permitir tudo para autenticados - ajustar conforme necessidade)
CREATE POLICY "Enable all access for authenticated users" ON airbnb_reviews
    FOR ALL USING (auth.role() = 'authenticated');
