-- Script gerado automaticamente

UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 1; -- Geraldo
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 3; -- Edson
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 4; -- Gelmer
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 5; -- Paulo
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 6; -- Fabrício
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 7; -- Jessica
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 8; -- Rafael
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 9; -- Nayla
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 10; -- Leandro
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 11; -- Maria
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 12; -- Patricia
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 13; -- Juliana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 14; -- Bruno
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 15; -- Erika
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 16; -- João
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 17; -- Adriano
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 18; -- Antônio
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 19; -- Julia
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 20; -- Mônica
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 21; -- Aline
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 22; -- Robison
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 23; -- Felipe
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 24; -- Ricardo
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 25; -- Lis
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 26; -- Daniela
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 27; -- Lais
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 28; -- Paula
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 29; -- Alana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 30; -- Rafaely
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 31; -- Ariana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 32; -- Juliana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 33; -- José
UPDATE airbnb_reviews SET accuracy_rating = 4 WHERE id = 34; -- Carlos
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 35; -- Marcelo
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 36; -- Luca
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 37; -- Mariana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 39; -- Roberto
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 40; -- Fabiano
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 41; -- Jéssica
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 42; -- Angélica
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 43; -- Luciana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 44; -- Junior
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 45; -- Natalie
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 46; -- Patricia
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 47; -- Flavia
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 48; -- Arielle
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 49; -- Ana
UPDATE airbnb_reviews SET accuracy_rating = 5 WHERE id = 50; -- Steffanie
